CREATE TABLE user (
  userID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(100) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Enabled BOOLEAN DEFAULT TRUE,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role (
  roleID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE address (
  addressID INT PRIMARY KEY AUTO_INCREMENT,
  Calle VARCHAR(100),
  Ciudad VARCHAR(100),
  Pais VARCHAR(100),
  CodigoPostal VARCHAR(20),
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES user(userID)
);

CREATE TABLE category (
  categoryID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(100) NOT NULL,
  Descripcion TEXT
);

CREATE TABLE book (
  bookID INT PRIMARY KEY AUTO_INCREMENT,
  Titulo VARCHAR(150) NOT NULL,
  Autor VARCHAR(100),
  Precio DECIMAL(10,2),
  Stock INT DEFAULT 0,
  CategoryID INT,
  FOREIGN KEY (CategoryID) REFERENCES category(categoryID)
);

CREATE TABLE review (
  reviewID INT PRIMARY KEY AUTO_INCREMENT,
  Contenido TEXT,
  Rating INT CHECK (Rating BETWEEN 1 AND 5),
  UserID INT,
  BookID INT,
  FOREIGN KEY (UserID) REFERENCES user(userID),
  FOREIGN KEY (BookID) REFERENCES book(bookID)
);

CREATE TABLE cart (
  cartID INT PRIMARY KEY AUTO_INCREMENT,
  UserID INT,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES user(userID)
);

CREATE TABLE cart_item (
  cartItemID INT PRIMARY KEY AUTO_INCREMENT,
  Cantidad INT NOT NULL,
  BookID INT,
  CartID INT,
  FOREIGN KEY (BookID) REFERENCES book(bookID),
  FOREIGN KEY (CartID) REFERENCES cart(cartID)
);

CREATE TABLE `order` (
  orderID INT PRIMARY KEY AUTO_INCREMENT,
  Fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
  Total DECIMAL(10,2),
  Estado VARCHAR(50),
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES user(userID)
);

CREATE TABLE order_item (
  orderItemID INT PRIMARY KEY AUTO_INCREMENT,
  Cantidad INT NOT NULL,
  PrecioUnitario DECIMAL(10,2),
  BookID INT,
  OrderID INT,
  FOREIGN KEY (BookID) REFERENCES book(bookID),
  FOREIGN KEY (OrderID) REFERENCES `order`(orderID)
);
